//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDallphaModel : DbContext
    {
        public BDallphaModel()
            : base("name=BDallphaModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompraT> CompraT { get; set; }
        public virtual DbSet<LogsT> LogsT { get; set; }
        public virtual DbSet<TbAlbum> TbAlbum { get; set; }
        public virtual DbSet<TbUser> TbUser { get; set; }
        public virtual DbSet<TrackT> TrackT { get; set; }
    }
}
